#include "hostmodule.hpp"


DECLARE_MODULE_INFORMATION_BEGIN
DECLARE_MODULE_INFORMATION_NAME("HostModule"),
DECLARE_MODULE_INFORMATION_VERSION(0),
DECLARE_MODULE_INFORMATION_SUBVERSION(0),
DECLARE_MODULE_INFORMATION_PATCH(0)
DECLARE_MODULE_INFORMATION_END
DECLARE_MODULE_INFORMATION_GETTER(HostModule)

bool HostModule::start()
{
	return false;
}

bool HostModule::stop()
{
	return false;
}
